version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: my-mongo
    ports:
      - "27017:27017"

  grafana:
    image: grafana/grafana:latest
    container_name: my-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-mongodb-datasource

