{
 "title": "Mongo Diagnostics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Build Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "admin.buildInfo({\"version\": 1, \"buildEnvironment.target_os\": 1, \"buildEnvironment.target_arch\": 1})"
    }
   ]
  },
  {
   "title": "Server Status - Atlas Metrics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "admin.serverStatus({metrics: 1})"
    }
   ]
  },
  {
   "title": "Server Status - Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "admin.serverStatus({connections: 1})"
    }
   ]
  },
  {
   "title": "Server Status - Replication Write",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "query": "admin.serverStatus({\"repl.lastWrite.lastWriteDate\": 1, \"repl.lastWrite.opTime.t\": 1})"
    }
   ]
  },
  {
   "title": "Server Status - Network",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "admin.serverStatus({network: 1})"
    }
   ]
  },
  {
   "title": "Server Status - Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "query": "admin.serverStatus({mem: 1})" }
   ]
  },
  {
   "title": "Connection Status - Authenticated User Roles",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 2, "y": 13 },
   "targets": [
    {
     "query": "admin.connectionStatus({\"authInfo.authenticatedUserRoles\": 1})"
    }
   ]
  },
  {
   "title": "Connection Status - Authenticated Users",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 13 },
   "targets": [
    {
     "query": "admin.connectionStatus({\"authInfo.authenticatedUsers\": 1})"
    }
   ]
  },
  {
   "title": "Connection Pool Stats - Pools",
   "type": "stat",
   "gridPos": { "h": 5, "w": 19, "x": 2, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "admin.connPoolStats({arg: \"pools\"})"
    }
   ]
  },
  {
   "title": "MFlix Database Stats",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "query": "sample_mflix.stats()" }
   ]
  }
 ]
}