{
 "title": "Mongo Movies",
 "time": { "from": "now-20y", "to": "now-6y" },
 "panels": [
  {
   "title": "Movies Produced Per Year",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "sample_mflix.movies.aggregate([\n    {\"$match\": { \"year\": {\"$gt\" : 2000} }},\n    {\"$group\": { \"_id\": \"$year\", \"count\": { \"$sum\": 1 }}},\n    {\"$project\": { \"_id\": 0, \"count\": 1, \"time\": { \"$dateFromParts\": {\"year\": \"$_id\", \"month\": 2}}}}\n    ]\n ).sort({\"time\": 1})\n"
    }
   ]
  },
  {
   "title": "Movie Count by Rating",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "sample_mflix.movies.aggregate([\n\t\t{\"$match\": { \"year\": 2015 }},\n\t\t{\"$group\": { \"_id\": \"$rated\", \"count\": { \"$sum\": 1 } }},\n \t\t{\"$project\": { \"rating\": \"$_id\", \"_id\": 0, \"count\": 1 }}\n    ],\n    {\n      cursor: { batchSize: 0 }\n    }\n).sort({count: 0})"
    }
   ]
  },
  {
   "title": "Recent Movies",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "sample_mflix.movies.find({year: {$gt:2010}, released: {$ne: null}},{\"released\":1,\"_id\":0,title: 1, year: 1, rated: 1}).limit(1000).sort({\"year\": -1})"
    }
   ]
  }
 ]
}