#Using official python base image
FROM python:3.9-slim

#Copy the current directory contents into the container
COPY . /app

#Set working directory
WORKDIR /app

#Run the script
CMD ["python","app.py"]



